// Code generated by goctl. DO NOT EDIT.
// Source: interaction.proto

package server

import (
	"context"

	"douyin-interaction/internal/logic"
	"douyin-interaction/internal/svc"
	"douyin-interaction/types"
)

type InteractionServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedInteractionServer
}

func NewInteractionServer(svcCtx *svc.ServiceContext) *InteractionServer {
	return &InteractionServer{
		svcCtx: svcCtx,
	}
}

func (s *InteractionServer) FavoriteAction(ctx context.Context, in *__.DouyinFavoriteActionRequest) (*__.DouyinFavoriteActionResponse, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}

func (s *InteractionServer) FavoriteList(ctx context.Context, in *__.DouyinFavoriteListRequest) (*__.DouyinFavoriteListResponse, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}

func (s *InteractionServer) CommentAction(ctx context.Context, in *__.DouyinCommentActionRequest) (*__.DouyinCommentActionResponse, error) {
	l := logic.NewCommentActionLogic(ctx, s.svcCtx)
	return l.CommentAction(in)
}

func (s *InteractionServer) CommentList(ctx context.Context, in *__.DouyinCommentListRequest) (*__.DouyinCommentListResponse, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
