// Code generated by goctl. DO NOT EDIT.
// Source: interaction.proto

package interaction

import (
	"context"

	"douyin-interaction/types"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment                      = __.Comment
	DouyinCommentActionRequest   = __.DouyinCommentActionRequest
	DouyinCommentActionResponse  = __.DouyinCommentActionResponse
	DouyinCommentListRequest     = __.DouyinCommentListRequest
	DouyinCommentListResponse    = __.DouyinCommentListResponse
	DouyinFavoriteActionRequest  = __.DouyinFavoriteActionRequest
	DouyinFavoriteActionResponse = __.DouyinFavoriteActionResponse
	DouyinFavoriteListRequest    = __.DouyinFavoriteListRequest
	DouyinFavoriteListResponse   = __.DouyinFavoriteListResponse
	User                         = __.User
	Video                        = __.Video

	Interaction interface {
		FavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...grpc.CallOption) (*DouyinFavoriteActionResponse, error)
		FavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, opts ...grpc.CallOption) (*DouyinFavoriteListResponse, error)
		CommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error)
		CommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error)
	}

	defaultInteraction struct {
		cli zrpc.Client
	}
)

func NewInteraction(cli zrpc.Client) Interaction {
	return &defaultInteraction{
		cli: cli,
	}
}

func (m *defaultInteraction) FavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...grpc.CallOption) (*DouyinFavoriteActionResponse, error) {
	client := __.NewInteractionClient(m.cli.Conn())
	return client.FavoriteAction(ctx, in, opts...)
}

func (m *defaultInteraction) FavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, opts ...grpc.CallOption) (*DouyinFavoriteListResponse, error) {
	client := __.NewInteractionClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}

func (m *defaultInteraction) CommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error) {
	client := __.NewInteractionClient(m.cli.Conn())
	return client.CommentAction(ctx, in, opts...)
}

func (m *defaultInteraction) CommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error) {
	client := __.NewInteractionClient(m.cli.Conn())
	return client.CommentList(ctx, in, opts...)
}
